version: "3.7"

x-env_file: &env_file
  env_file:
    - ./.env

services:
  web:
    <<: *env_file
    build: .
    tty: true
    stdin_open: true
    ports:
      - 8001:8001
    restart: always
    container_name: book-collection-api
    volumes:
      - ./app/:/app
    depends_on:
      - db

  db:
    <<: *env_file
    image: postgres:latest
    restart: always
    volumes:
    - postgres-data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    container_name: book-collection-postgres

volumes:
  postgres-data:

networks:
  default:
    external:
      name: book-collection-network
